name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Hugo
      run: sudo apt-get install hugo
    - name: Deploy
      run: |
        SSH_DIR="${HOME}/.ssh"
        mkdir "${SSH_DIR}"
        ssh-keyscan -t rsa github.com > "${SSH_DIR}/known_hosts"
        echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > "${SSH_DIR}/id_rsa"
        chmod 400 "${SSH_DIR}/id_rsa"
        git remote set-url origin git@github.com:dreamvo/whitepaper.git
        git config --global user.name "dreamvo"
        git config --global user.email "dreamvo@users.noreply.github.com"
        sh ./scripts/deploy.sh
